Squash of index-md5 branch (#732), includes all commits of #725
commit 269347dffc75128bf0b4e92caaef2448d3086a6f
Author: Dipanjan Mukherjee <dipanjanm@fb.com>
Date:   Tue Jul 27 19:34:42 2021 +0000

    terraform the unified indexer; remove pdq_indexer

commit 018fbf91b56fbf31f70524476bdfac90e17d7da3
Author: Dipanjan Mukherjee <dipanjanm@fb.com>
Date:   Tue Jul 27 19:34:20 2021 +0000

    Add a unified indexer lambda that will index all supported indicator types from threatexchange

    At this point:
    PDQ and MD5. But easily extendable to more.

commit 52454482fd81085d368d7aeec5da70526c253a73
Author: Dipanjan Mukherjee <dipanjanm@fb.com>
Date:   Tue Jul 27 19:33:07 2021 +0000

    Encapsulate index saving / loading into dedicated module

commit dcc7e8e531440c30a12967fce1dc6c540e9feee2
Author: Dipanjan Mukherjee <dipanjanm@fb.com>
Date:   Tue Jul 27 19:32:06 2021 +0000

    Internalize signal_type to datafile key in s3_adapters

    Also provide a reversing function to test whether an s3 key provides threatexchange data.

commit 7bfddb36ce0622002dbdb563314a43ca283db18e
Author: Dipanjan Mukherjee <dipanjanm@fb.com>
Date:   Fri Jul 23 20:46:15 2021 +0000

    Move ThreatUpdateS3Store to s3_adapters.py

    There is potential for re-use of the same class between indexer, matcher and fetcher. Having a single place for everything to do with signal storage makes refactors easier.

commit bdab484a301b6028b06a29ce320da1bc787bd4b5
Author: Dipanjan Mukherjee <dipanjanm@fb.com>
Date:   Fri Jul 23 20:27:43 2021 +0000

    [md5-fetcher] Fetch indicators of type MD5 in fetcher.py

commit ae27fb314de4415a2931cdbeb8255ebe36fdc687
Author: Dipanjan Mukherjee <dipanjanm@fb.com>
Date:   Wed Jul 21 13:54:11 2021 -0400

    [threatexchange][hotfix] Missing function invocation in `threatexchange.content_type.meta.get_content_type_for_name` (#724)

    Summary
    ---
    Also bumps version to 0.0.22. 0.0.21 should be considered poisoned.

    Test Plan
    ---
    ```
    >>> from threatexchange.content_type.meta import get_content_type_for_name
    >>> get_content_type_for_name('photo')
    ```

    Before

    ```
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/workspaces/ThreatExchange/python-threatexchange/threatexchange/content_type/meta.py", line 53, in get_content_type_for_name
        return _get_content_type_map[name]
    TypeError: 'functools._lru_cache_wrapper' object is not subscriptable
    ```

    After

    ```
    <class 'threatexchange.content_type.photo.PhotoContent'>
    ```