[hma] ThreatExchang/Collaboration config in HMAConfig, Helper Populate script (#499)
Summary
---------

* Adds ThreatExchangeConfig
* Add a script to make it easy to populate test data (since old script doesn't work)

Doesn't actually pull the trigger on moving the rest over to give @mengyangwang  a chance to do more in #494 

Test Plan
---------

```
$  python -m hmalib.scripts.populate_config_db --help
usage: populate_config_db.py [-h] [--table TABLE] {update,load_example_configs,get} ...

Write simple configs to the HMA config database

positional arguments:
  {update,load_example_configs,get}
    update              Add or edit a config
    load_example_configs
                        Populate db with a default set of configs
    get                 get configs

optional arguments:
  -h, --help            show this help message and exit
  --table TABLE         The name of the config dynamodb table

$ python -m hmalib.scripts.populate_config_db update --help
usage: populate_config_db.py update [-h] {ThreatExchangeConfig} ...

positional arguments:
  {ThreatExchangeConfig}
    ThreatExchangeConfig
                        Update a config of this type

optional arguments:
  -h, --help            show this help message and exit

$ python -m hmalib.scripts.populate_config_db update ThreatExchangeConfig --help
usage: populate_config_db.py update ThreatExchangeConfig [-h] --enabled bool --privacy_group int str

positional arguments:
  str                  name

optional arguments:
  -h, --help           show this help message and exit
  --enabled bool       enabled
  --privacy_group int  privacy_group

$ python -m hmalib.scripts.populate_config_db update ThreatExchangeConfig Test --enabled false --privacy_group 1234
ThreatExchangeConfig(name='Test', enabled=False, privacy_group=1234)

$ python -m hmalib.scripts.populate_config_db load_example_configs
ThreatExchangeConfig(name='Test Config 1', enabled=False, privacy_group=303636684709969)
ThreatExchangeConfig(name='Test Config 2', enabled=False, privacy_group=258601789084078)

$ ThreatExchangeConfig(name='Test', enabled=False, privacy_group=1234)
ThreatExchangeConfig(name='Test Config 1', enabled=False, privacy_group=303636684709969)
ThreatExchangeConfig(name='Test Config 2', enabled=False, privacy_group=258601789084078)

$ python -m hmalib.scripts.populate_config_db get ThreatExchangeConfig --name Test
ThreatExchangeConfig(name='Test', enabled=False, privacy_group=1234)

$ python -m hmalib.scripts.populate_config_db get ThreatExchangeConfig --name Noexist
Traceback (most recent call last):
...
ValueError: No ThreatExchangeConfig named Noexist
```