[threatexchange][hotfix] Missing function invocation in `threatexchange.content_type.meta.get_content_type_for_name` (#724)
Summary
---
Also bumps version to 0.0.22. 0.0.21 should be considered poisoned.

Test Plan
---
```
>>> from threatexchange.content_type.meta import get_content_type_for_name
>>> get_content_type_for_name('photo')
```

Before

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspaces/ThreatExchange/python-threatexchange/threatexchange/content_type/meta.py", line 53, in get_content_type_for_name
    return _get_content_type_map[name]
TypeError: 'functools._lru_cache_wrapper' object is not subscriptable
```

After

```
<class 'threatexchange.content_type.photo.PhotoContent'>
```