[threatexchange] Remove unused imports throwing circular import exception
Test
---
Before:
```
>>>  from threatexchange.signal_type.signal_base import SignalType
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/workspaces/ThreatExchange/python-threatexchange/threatexchange/signal_type/signal_base.py", line 14, in <module>
    from .. import dataset
  File "/workspaces/ThreatExchange/python-threatexchange/threatexchange/dataset.py", line 18, in <module>
    from .content_type import meta
  File "/workspaces/ThreatExchange/python-threatexchange/threatexchange/content_type/meta.py", line 11, in <module>
    from . import content_base, text, video, photo
  File "/workspaces/ThreatExchange/python-threatexchange/threatexchange/content_type/content_base.py", line 13, in <module>
    from ..signal_type import signal_base, raw_text, trend_query, url
  File "/workspaces/ThreatExchange/python-threatexchange/threatexchange/signal_type/raw_text.py", line 19, in <module>
    class RawTextSignal(signal_base.SimpleSignalType, signal_base.StrMatcher):
AttributeError: partially initialized module 'threatexchange.signal_type.signal_base' has no attribute 'SimpleSignalType' (most likely due to a circular import)
```

Now:
```
>>> from threatexchange.signal_type.signal_base import SignalType
>>>
```